version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - zip -r myapp.zip .
      - unzip $FILE_NAME -d extracted_files/

artifacts:
  files:
    - myapp.zip
  base-directory: extracted_files

