version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14  # You can change this to your desired Node.js version
    commands:
      - echo Installing dependencies...
      - npm install  # Install project dependencies defined in package.json
  build:
    commands:
      - echo Running lint...
      - npm run lint  # If you have linting configured (e.g., ESLint)
      - echo Running tests...
      - npm run test  # Run tests (adjust if you're using a testing framework like Jest, Mocha, etc.)
  post_build:
    commands:
      - echo Build complete
      - echo Creating build artifacts...
      - mkdir -p output  # Create a directory to store build artifacts
artifacts:
  files:
    - '**/*'  # Include all files in the output directory
  base-directory: output  # Specify the base directory for the artifacts
  discard-paths: yes  # Optionally discard folder structure for your artifacts
