{\rtf1\ansi\ansicpg1252\cocoartf2820
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\paperw11900\paperh16840\margl1440\margr1440\vieww28300\viewh17140\viewkind0
\pard\tx566\tx1133\tx1700\tx2267\tx2834\tx3401\tx3968\tx4535\tx5102\tx5669\tx6236\tx6803\pardirnatural\partightenfactor0

\f0\fs24 \cf0 version: 0.2\
\
phases:\
  install:\
    runtime-versions:\
      nodejs: 14  # You can change this to your desired Node.js version\
    commands:\
      - echo Installing dependencies...\
      - npm install  # Install project dependencies defined in package.json\
  build:\
    commands:\
      - echo Running lint...\
      - npm run lint  # If you have linting configured (e.g., ESLint)\
      - echo Running tests...\
      - npm run test  # Run tests (adjust if you're using a testing framework like Jest, Mocha, etc.)\
  post_build:\
    commands:\
      - echo Build complete\
      - echo Creating build artifacts...\
      - mkdir -p output  # Create a directory to store build artifacts\
      - cp -r * output/  # Copy the application files to the output directory for deployment\
artifacts:\
  files:\
    - '**/*'  # Include all files in the output directory\
  base-directory: output  # Specify the base directory for the artifacts\
  discard-paths: yes  # Optionally discard folder structure for your artifacts\
}